site_name: AincradOT foundation
site_url: https://AincradOT.github.io/foundation
repo_url: https://github.com/AincradOT/foundation
edit_uri: edit/master/docs/

theme:
  name: material

docs_dir: ../docs

nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Workflows: workflows.md
  - Contributing: contributing.md
  - Documentation: documentation.md
